// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared.proto

package gitalypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import google_protobuf1 "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CoordinatorMsg_Operation int32

const (
	CoordinatorMsg_READ  CoordinatorMsg_Operation = 0
	CoordinatorMsg_WRITE CoordinatorMsg_Operation = 1
)

var CoordinatorMsg_Operation_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}
var CoordinatorMsg_Operation_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x CoordinatorMsg_Operation) String() string {
	return proto.EnumName(CoordinatorMsg_Operation_name, int32(x))
}
func (CoordinatorMsg_Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor12, []int{0, 0} }

type CoordinatorMsg struct {
	Op CoordinatorMsg_Operation `protobuf:"varint,1,opt,name=op,enum=gitaly.CoordinatorMsg_Operation" json:"op,omitempty"`
}

func (m *CoordinatorMsg) Reset()                    { *m = CoordinatorMsg{} }
func (m *CoordinatorMsg) String() string            { return proto.CompactTextString(m) }
func (*CoordinatorMsg) ProtoMessage()               {}
func (*CoordinatorMsg) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{0} }

func (m *CoordinatorMsg) GetOp() CoordinatorMsg_Operation {
	if m != nil {
		return m.Op
	}
	return CoordinatorMsg_READ
}

type Repository struct {
	StorageName  string `protobuf:"bytes,2,opt,name=storage_name,json=storageName" json:"storage_name,omitempty"`
	RelativePath string `protobuf:"bytes,3,opt,name=relative_path,json=relativePath" json:"relative_path,omitempty"`
	// Sets the GIT_OBJECT_DIRECTORY envvar on git commands to the value of this field.
	// It influences the object storage directory the SHA1 directories are created underneath.
	GitObjectDirectory string `protobuf:"bytes,4,opt,name=git_object_directory,json=gitObjectDirectory" json:"git_object_directory,omitempty"`
	// Sets the GIT_ALTERNATE_OBJECT_DIRECTORIES envvar on git commands to the values of this field.
	// It influences the list of Git object directories which can be used to search for Git objects.
	GitAlternateObjectDirectories []string `protobuf:"bytes,5,rep,name=git_alternate_object_directories,json=gitAlternateObjectDirectories" json:"git_alternate_object_directories,omitempty"`
	// Used in callbacks to GitLab so that it knows what repository the event is
	// associated with. May be left empty on RPC's that do not perform callbacks.
	GlRepository string `protobuf:"bytes,6,opt,name=gl_repository,json=glRepository" json:"gl_repository,omitempty"`
}

func (m *Repository) Reset()                    { *m = Repository{} }
func (m *Repository) String() string            { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()               {}
func (*Repository) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{1} }

func (m *Repository) GetStorageName() string {
	if m != nil {
		return m.StorageName
	}
	return ""
}

func (m *Repository) GetRelativePath() string {
	if m != nil {
		return m.RelativePath
	}
	return ""
}

func (m *Repository) GetGitObjectDirectory() string {
	if m != nil {
		return m.GitObjectDirectory
	}
	return ""
}

func (m *Repository) GetGitAlternateObjectDirectories() []string {
	if m != nil {
		return m.GitAlternateObjectDirectories
	}
	return nil
}

func (m *Repository) GetGlRepository() string {
	if m != nil {
		return m.GlRepository
	}
	return ""
}

// Corresponds to Gitlab::Git::Commit
type GitCommit struct {
	Id        string        `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Subject   []byte        `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body      []byte        `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Author    *CommitAuthor `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	Committer *CommitAuthor `protobuf:"bytes,5,opt,name=committer" json:"committer,omitempty"`
	ParentIds []string      `protobuf:"bytes,6,rep,name=parent_ids,json=parentIds" json:"parent_ids,omitempty"`
	// If body exceeds a certain threshold, it will be nullified,
	// but its size will be set in body_size so we can know if
	// a commit had a body in the first place.
	BodySize int64 `protobuf:"varint,7,opt,name=body_size,json=bodySize" json:"body_size,omitempty"`
}

func (m *GitCommit) Reset()                    { *m = GitCommit{} }
func (m *GitCommit) String() string            { return proto.CompactTextString(m) }
func (*GitCommit) ProtoMessage()               {}
func (*GitCommit) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{2} }

func (m *GitCommit) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GitCommit) GetSubject() []byte {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *GitCommit) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *GitCommit) GetAuthor() *CommitAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *GitCommit) GetCommitter() *CommitAuthor {
	if m != nil {
		return m.Committer
	}
	return nil
}

func (m *GitCommit) GetParentIds() []string {
	if m != nil {
		return m.ParentIds
	}
	return nil
}

func (m *GitCommit) GetBodySize() int64 {
	if m != nil {
		return m.BodySize
	}
	return 0
}

type CommitAuthor struct {
	Name  []byte                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email []byte                     `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Date  *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=date" json:"date,omitempty"`
}

func (m *CommitAuthor) Reset()                    { *m = CommitAuthor{} }
func (m *CommitAuthor) String() string            { return proto.CompactTextString(m) }
func (*CommitAuthor) ProtoMessage()               {}
func (*CommitAuthor) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{3} }

func (m *CommitAuthor) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *CommitAuthor) GetEmail() []byte {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *CommitAuthor) GetDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

type ExitStatus struct {
	Value int32 `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *ExitStatus) Reset()                    { *m = ExitStatus{} }
func (m *ExitStatus) String() string            { return proto.CompactTextString(m) }
func (*ExitStatus) ProtoMessage()               {}
func (*ExitStatus) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{4} }

func (m *ExitStatus) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Corresponds to Gitlab::Git::Branch
type Branch struct {
	Name         []byte     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TargetCommit *GitCommit `protobuf:"bytes,2,opt,name=target_commit,json=targetCommit" json:"target_commit,omitempty"`
}

func (m *Branch) Reset()                    { *m = Branch{} }
func (m *Branch) String() string            { return proto.CompactTextString(m) }
func (*Branch) ProtoMessage()               {}
func (*Branch) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{5} }

func (m *Branch) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Branch) GetTargetCommit() *GitCommit {
	if m != nil {
		return m.TargetCommit
	}
	return nil
}

type Tag struct {
	Name         []byte     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id           string     `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	TargetCommit *GitCommit `protobuf:"bytes,3,opt,name=target_commit,json=targetCommit" json:"target_commit,omitempty"`
	// If message exceeds a certain threshold, it will be nullified,
	// but its size will be set in message_size so we can know if
	// a tag had a message in the first place.
	Message     []byte        `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	MessageSize int64         `protobuf:"varint,5,opt,name=message_size,json=messageSize" json:"message_size,omitempty"`
	Tagger      *CommitAuthor `protobuf:"bytes,6,opt,name=tagger" json:"tagger,omitempty"`
}

func (m *Tag) Reset()                    { *m = Tag{} }
func (m *Tag) String() string            { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()               {}
func (*Tag) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{6} }

func (m *Tag) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Tag) GetTargetCommit() *GitCommit {
	if m != nil {
		return m.TargetCommit
	}
	return nil
}

func (m *Tag) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Tag) GetMessageSize() int64 {
	if m != nil {
		return m.MessageSize
	}
	return 0
}

func (m *Tag) GetTagger() *CommitAuthor {
	if m != nil {
		return m.Tagger
	}
	return nil
}

type User struct {
	GlId       string `protobuf:"bytes,1,opt,name=gl_id,json=glId" json:"gl_id,omitempty"`
	Name       []byte `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email      []byte `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	GlUsername string `protobuf:"bytes,4,opt,name=gl_username,json=glUsername" json:"gl_username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor12, []int{7} }

func (m *User) GetGlId() string {
	if m != nil {
		return m.GlId
	}
	return ""
}

func (m *User) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *User) GetEmail() []byte {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetGlUsername() string {
	if m != nil {
		return m.GlUsername
	}
	return ""
}

var E_OpType = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf1.MessageOptions)(nil),
	ExtensionType: (*CoordinatorMsg)(nil),
	Field:         82305,
	Name:          "gitaly.op_type",
	Tag:           "bytes,82305,opt,name=op_type,json=opType",
	Filename:      "shared.proto",
}

func init() {
	proto.RegisterType((*CoordinatorMsg)(nil), "gitaly.CoordinatorMsg")
	proto.RegisterType((*Repository)(nil), "gitaly.Repository")
	proto.RegisterType((*GitCommit)(nil), "gitaly.GitCommit")
	proto.RegisterType((*CommitAuthor)(nil), "gitaly.CommitAuthor")
	proto.RegisterType((*ExitStatus)(nil), "gitaly.ExitStatus")
	proto.RegisterType((*Branch)(nil), "gitaly.Branch")
	proto.RegisterType((*Tag)(nil), "gitaly.Tag")
	proto.RegisterType((*User)(nil), "gitaly.User")
	proto.RegisterEnum("gitaly.CoordinatorMsg_Operation", CoordinatorMsg_Operation_name, CoordinatorMsg_Operation_value)
	proto.RegisterExtension(E_OpType)
}

func init() { proto.RegisterFile("shared.proto", fileDescriptor12) }

var fileDescriptor12 = []byte{
	// 690 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0x25, 0x4d, 0xbb, 0xe6, 0x36, 0x9b, 0xf6, 0x33, 0x13, 0x8a, 0x86, 0xa6, 0x85, 0xf0,
	0xd2, 0x07, 0x94, 0x4d, 0x45, 0xe2, 0x81, 0xb7, 0xfd, 0xd3, 0x34, 0xa4, 0x31, 0xe4, 0x75, 0x42,
	0xe2, 0x25, 0x72, 0x1b, 0xcf, 0x35, 0x4a, 0xea, 0xc8, 0x76, 0x27, 0xba, 0x27, 0x10, 0x5f, 0x8f,
	0xef, 0xc1, 0xd7, 0x40, 0xb6, 0x9b, 0xee, 0x5f, 0x41, 0xbc, 0xf9, 0x5e, 0x1f, 0xdf, 0x7b, 0x8f,
	0xcf, 0xb1, 0x21, 0x52, 0x13, 0x22, 0x69, 0x91, 0xd5, 0x52, 0x68, 0x81, 0x3a, 0x8c, 0x6b, 0x52,
	0xce, 0xb7, 0x77, 0x99, 0x10, 0xac, 0xa4, 0x7b, 0x36, 0x3b, 0x9a, 0x5d, 0xef, 0x69, 0x5e, 0x51,
	0xa5, 0x49, 0x55, 0x3b, 0xe0, 0x76, 0xf2, 0x18, 0x50, 0x50, 0x35, 0x96, 0xbc, 0xd6, 0x42, 0x3a,
	0x44, 0x5a, 0xc0, 0xc6, 0x91, 0x10, 0xb2, 0xe0, 0x53, 0xa2, 0x85, 0x3c, 0x57, 0x0c, 0xed, 0x83,
	0x2f, 0xea, 0xd8, 0x4b, 0xbc, 0xfe, 0xc6, 0x20, 0xc9, 0x5c, 0xa7, 0xec, 0x21, 0x26, 0xbb, 0xa8,
	0xa9, 0x24, 0x9a, 0x8b, 0x29, 0xf6, 0x45, 0x9d, 0x26, 0x10, 0x2e, 0x13, 0xa8, 0x0b, 0x01, 0x3e,
	0x39, 0x38, 0xde, 0xfc, 0x0f, 0x85, 0xd0, 0xfe, 0x84, 0xcf, 0x86, 0x27, 0x9b, 0x5e, 0xfa, 0xcd,
	0x07, 0xc0, 0xb4, 0x16, 0x8a, 0x6b, 0x21, 0xe7, 0xe8, 0x25, 0x44, 0x4a, 0x0b, 0x49, 0x18, 0xcd,
	0xa7, 0xa4, 0xa2, 0xb1, 0x9f, 0x78, 0xfd, 0x10, 0xf7, 0x16, 0xb9, 0x0f, 0xa4, 0xa2, 0xe8, 0x15,
	0xac, 0x4b, 0x5a, 0x12, 0xcd, 0x6f, 0x68, 0x5e, 0x13, 0x3d, 0x89, 0x5b, 0x16, 0x13, 0x35, 0xc9,
	0x8f, 0x44, 0x4f, 0xd0, 0x3e, 0x6c, 0x31, 0xae, 0x73, 0x31, 0xfa, 0x42, 0xc7, 0x3a, 0x2f, 0xb8,
	0xa4, 0x63, 0x53, 0x3f, 0x0e, 0x2c, 0x16, 0x31, 0xae, 0x2f, 0xec, 0xd6, 0x71, 0xb3, 0x83, 0x4e,
	0x21, 0x31, 0x27, 0x48, 0xa9, 0xa9, 0x9c, 0x12, 0x4d, 0x1f, 0x9f, 0xe5, 0x54, 0xc5, 0xed, 0xa4,
	0xd5, 0x0f, 0xf1, 0x0e, 0xe3, 0xfa, 0xa0, 0x81, 0x3d, 0x2c, 0xc3, 0xa9, 0x32, 0xf3, 0xb1, 0x32,
	0x97, 0x4b, 0x4e, 0x71, 0xc7, 0xcd, 0xc7, 0xca, 0x3b, 0x9e, 0xef, 0x83, 0xae, 0xb7, 0xe9, 0xe3,
	0xc0, 0xcc, 0x9f, 0xfe, 0xf2, 0x20, 0x3c, 0xe5, 0xfa, 0x48, 0x54, 0x15, 0xd7, 0x68, 0x03, 0x7c,
	0x5e, 0xd8, 0x4b, 0x0e, 0xb1, 0xcf, 0x0b, 0x14, 0xc3, 0x9a, 0x9a, 0xd9, 0x26, 0xf6, 0x32, 0x22,
	0xdc, 0x84, 0x08, 0x41, 0x30, 0x12, 0xc5, 0xdc, 0xf2, 0x8f, 0xb0, 0x5d, 0xa3, 0xd7, 0xd0, 0x21,
	0x33, 0x3d, 0x11, 0xd2, 0x32, 0xed, 0x0d, 0xb6, 0xee, 0x64, 0x32, 0xd5, 0x0f, 0xec, 0x1e, 0x5e,
	0x60, 0xd0, 0x00, 0xc2, 0xb1, 0xcd, 0x6b, 0x2a, 0xe3, 0xf6, 0x5f, 0x0e, 0xdc, 0xc1, 0xd0, 0x0e,
	0x40, 0x4d, 0x24, 0x9d, 0xea, 0x9c, 0x17, 0x2a, 0xee, 0xd8, 0x1b, 0x09, 0x5d, 0xe6, 0xac, 0x50,
	0xe8, 0x05, 0x84, 0x66, 0x90, 0x5c, 0xf1, 0x5b, 0x1a, 0xaf, 0x25, 0x5e, 0xbf, 0x85, 0xbb, 0x26,
	0x71, 0xc9, 0x6f, 0x69, 0x3a, 0x81, 0xe8, 0x7e, 0x59, 0xc3, 0xc0, 0xaa, 0xec, 0x39, 0x06, 0x66,
	0x8d, 0xb6, 0xa0, 0x4d, 0x2b, 0xc2, 0xcb, 0x05, 0x5b, 0x17, 0xa0, 0x0c, 0x82, 0x82, 0x68, 0x6a,
	0xb9, 0xf6, 0x06, 0xdb, 0x99, 0x73, 0x6f, 0xd6, 0xb8, 0x37, 0x1b, 0x36, 0xf6, 0xc6, 0x16, 0x97,
	0xa6, 0x00, 0x27, 0x5f, 0xb9, 0xbe, 0xd4, 0x44, 0xcf, 0x94, 0xa9, 0x79, 0x43, 0xca, 0x99, 0x6b,
	0xd4, 0xc6, 0x2e, 0x48, 0x87, 0xd0, 0x39, 0x94, 0x64, 0x3a, 0x9e, 0xac, 0x9c, 0xe3, 0x2d, 0xac,
	0x6b, 0x22, 0x19, 0xd5, 0xb9, 0xe3, 0x6e, 0xe7, 0xe9, 0x0d, 0xfe, 0x6f, 0xee, 0x67, 0xa9, 0x18,
	0x8e, 0x1c, 0xce, 0x45, 0xe9, 0x4f, 0x0f, 0x5a, 0x43, 0xc2, 0x56, 0xd6, 0x74, 0xda, 0xfa, 0x4b,
	0x6d, 0x9f, 0xf4, 0x68, 0xfd, 0x53, 0x0f, 0xe3, 0x89, 0x8a, 0x2a, 0x45, 0x18, 0xb5, 0x32, 0x47,
	0xb8, 0x09, 0xcd, 0xfb, 0x59, 0x2c, 0x9d, 0x02, 0x6d, 0xab, 0x40, 0x6f, 0x91, 0x33, 0x22, 0x18,
	0x8b, 0x68, 0xc2, 0x18, 0x95, 0xd6, 0x98, 0x7f, 0xb4, 0x88, 0xc3, 0xa4, 0xd7, 0x10, 0x5c, 0x29,
	0x2a, 0xd1, 0x33, 0x68, 0xb3, 0x32, 0x5f, 0x3a, 0x33, 0x60, 0xe5, 0x59, 0xb1, 0xe4, 0xe8, 0xaf,
	0xd2, 0xaf, 0x75, 0x5f, 0xbf, 0x5d, 0xe8, 0xb1, 0x32, 0x9f, 0x29, 0xf3, 0x68, 0x2a, 0xba, 0x78,
	0x86, 0xc0, 0xca, 0xab, 0x45, 0xe6, 0x1d, 0x86, 0x35, 0x51, 0xe7, 0x7a, 0x5e, 0x53, 0xb4, 0xfb,
	0x44, 0xdd, 0x73, 0x37, 0xfe, 0x45, 0x6d, 0xfe, 0x11, 0x15, 0x7f, 0xff, 0xe1, 0xbc, 0xfa, 0x7c,
	0xf5, 0x1f, 0x84, 0x3b, 0xa2, 0x1e, 0xce, 0x6b, 0x7a, 0x08, 0x9f, 0xbb, 0x0e, 0x50, 0x8f, 0x46,
	0x1d, 0x5b, 0xec, 0xcd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x98, 0x1c, 0x37, 0x2f, 0x05,
	0x00, 0x00,
}
